In [11]:
function gs(A)
    n=length(A[1,:])
    m=length(A[:,1])
    Q=zeros(m,n)
    Q[:,1]=A[:,1]/norm(A[:,1])
    k=2
    while (k<=n)
        X= A[:,k] - sum([dot(A[:,k],Q[:,j])*Q[:,j] for j in 1:(k-1)])
        Q[:,k] = X/norm(X)
        k+=1
    end
    return Q , Q'*A
end

gs (generic function with 1 method)

In [12]:
A=[1 2
3 4
5 6]

3×2 Array{Int64,2}:
 1  2
 3  4
 5  6

In [6]:
Q,R= gs(A)

(
[0.169031 0.897085; 0.507093 0.276026; 0.845154 -0.345033],

[5.91608 1.33227e-15; 7.43736 0.828079])

In [7]:
Q

3×2 Array{Float64,2}:
 0.169031   0.897085
 0.507093   0.276026
 0.845154  -0.345033

In [13]:
q1,r1=gs(A)

(
[0.169031 0.897085; 0.507093 0.276026; 0.845154 -0.345033],

[5.91608 7.43736; 1.33227e-15 0.828079])

In [9]:
q1

3×2 Array{Float64,2}:
 0.169031   0.897085
 0.507093   0.276026
 0.845154  -0.345033

In [10]:
r1

2×2 Array{Float64,2}:
 5.91608  1.33227e-15
 7.43736  0.828079   