## Algoritmo QR baseado na ortonormalização de Gram-Schmidt

As colunas da matriz $A$ são linearmente independentes e vamos ortonormalizá-las.
Se $v_1\dots v_n$ são as colunas de $A$, começamos fazendo $w_1 = v_1/\|v_1\|$
e para cada $k$ entre $2$ e $n$ fazemos $x = v_k - \sum_{l=1}^{k-1} <v_k,w_l>w_l$ e finalmente $w_k=x/\|x\|$

In [1]:
function gs(A)
    n=length(A[1,:]) # numero de colunas de A
    m=length(A[:,1]) # numero de linhas de A
    Q=zeros(m,n) # inicialização da matriz Q
    Q[:,1]=A[:,1]/norm(A[:,1]) # primeira coluna
    k=2
    while (k<=n)
        X= A[:,k] - sum([dot(A[:,k],Q[:,j])*Q[:,j] for j in 1:(k-1)])
        Q[:,k] = X/norm(X)
        k+=1
    end
    return Q , Q'*A
end

gs (generic function with 1 method)

In [3]:
A=[1 2
3 4
5 6]

3×2 Array{Int64,2}:
 1  2
 3  4
 5  6

In [5]:
#Teste
@time q1,r1= gs(A)

  0.000163 seconds (29 allocations: 2.047 KB)


(
[0.169031 0.897085; 0.507093 0.276026; 0.845154 -0.345033],

[5.91608 7.43736; 1.33227e-15 0.828079])

In [8]:
# comparação com qr 
@time q2,r2 = qr(A)

  0.000214 seconds (36 allocations: 1.891 KB)


(
[-0.169031 0.897085; -0.507093 0.276026; -0.845154 -0.345033],

[-5.91608 -7.43736; 0.0 0.828079])

In [9]:
q2*r2

3×2 Array{Float64,2}:
 1.0  2.0
 3.0  4.0
 5.0  6.0

In [10]:
q1*r1

3×2 Array{Float64,2}:
 1.0  2.0
 3.0  4.0
 5.0  6.0

In [12]:
r1

2×2 Array{Float64,2}:
 5.91608      7.43736 
 1.33227e-15  0.828079