## reflexões de Householder

Dado um vetor $v$ não nulo de $\mathbb{R}^m$ com o produto interno canônico, podemos escrever $\mathbb{R}^m= <v> \oplus <v>^{\bot}$. A reflexão de Householder correspondente é a aplicação linear $H_v: \mathbb{R}^m \to \mathbb{R}^m$ tal que 
$H_{v}(v)=-v $ e $H_v(x)=x$ se $x\in <v>^{\bot}$. 

A matriz de $H_v$ é $H_v=I-2\frac{vv^\prime}{v^\prime v}$. Faremos abaixo o exercício: se $x\in \mathbb{R}^m$ é dado, achar a reflexão de Houseolder (o vetor $v$), tal que $H_v(x)= \|x\|e_1$.

In [1]:
function reflete(x)
    n=length(x)
    e1 = [1.;zeros(n-1)] 
    v= x - norm(x)*e1
    Q = eye(n) -2*(v*v')/(norm(v)^2)
    return Q
end


reflete (generic function with 1 method)

In [2]:
#teste da função
x=[3.;0;-3]
Q1 = reflete(x)

3×3 Array{Float64,2}:
  0.707107  0.0  -0.707107
  0.0       1.0   0.0     
 -0.707107  0.0  -0.707107

In [3]:
Q1*x

3-element Array{Float64,1}:
 4.24264    
 0.0        
 4.44089e-16

Agora vamos fazer a decomposição QR usando householder.

In [4]:
    # tipo de construção de matrizes
m=4 # tamanho da matriz
y=[2;-1] # vetor de dimensão menor m-2
Qm= [eye(2)  zeros(2,m-2); zeros(m-2,2) reflete(y)]

4×4 Array{Float64,2}:
 1.0  0.0   0.0        0.0     
 0.0  1.0   0.0        0.0     
 0.0  0.0   0.894427  -0.447214
 0.0  0.0  -0.447214  -0.894427

In [5]:
 function qrholder(A)
    A1=copy(A)
    m,n = size(A1)
    
    if n>m println("Isto pode dar errado por enquanto") end
    #Q=reflete(A1[:,1])
    Q=eye(m)
    for k in 1:n
        Qh= [eye(k-1) zeros(k-1, m-k+1);
            zeros(m-k+1,k-1) reflete(A1[k:end,k])]
        Q= Qh*Q
        A1=Q*A1
    end
    return Q,Q*A
end

        
    

qrholder (generic function with 1 method)

In [6]:
A=[1. 2; -1 0; 1 5]

3×2 Array{Float64,2}:
  1.0  2.0
 -1.0  0.0
  1.0  5.0

In [7]:
L,M= qrholder(A)

(
[0.57735 -0.57735 0.57735; -0.0936586 0.65561 0.749269; -0.811107 -0.486664 0.324443],

[1.73205 4.04145; 0.0 3.55903; 2.77556e-16 -4.44089e-16])

In [8]:
display(L)

3×3 Array{Float64,2}:
  0.57735    -0.57735   0.57735 
 -0.0936586   0.65561   0.749269
 -0.811107   -0.486664  0.324443

In [9]:
L*L'

3×3 Array{Float64,2}:
 1.0           0.0           5.55112e-17
 0.0           1.0          -1.11022e-16
 5.55112e-17  -1.11022e-16   1.0        

## Segundo Algoritmo de Householder
Este é um algoritmo mais eficiente que não clcula diretamente a matriz $Q$, só a matriz $R$

In [10]:
function qrhouseholder(A)
    R=copy(A)
    m,n = size(R)
    v=[]
    for k in 1:n
        x = R[k:m,k]
        y = x+sign(x[1])*norm(x)*[1.;zeros(m-k)]
        y =y*(1/norm(y))
        push!(v,y)
        R[k:m,k:n] = R[k:m,k:n] - 2*v[k]*(v[k]'*R[k:m,k:n]) 
    end
    return R,v
        
end   

qrhouseholder (generic function with 1 method)

In [11]:
#teste
A=[1. 2; -1 0; 1 5]

3×2 Array{Float64,2}:
  1.0  2.0
 -1.0  0.0
  1.0  5.0

In [12]:
R,v=qrhouseholder(A)

(
[-1.73205 -4.04145; 0.0 -3.55903; 0.0 4.44089e-16],

Any[[0.888074,-0.325058,0.325058],[0.900369,0.435127]])

In [13]:
R

3×2 Array{Float64,2}:
 -1.73205  -4.04145    
  0.0      -3.55903    
  0.0       4.44089e-16

In [14]:
v

2-element Array{Any,1}:
 [0.888074,-0.325058,0.325058]
 [0.900369,0.435127]          