In [1]:
C= {a,b}

LoadError: syntax: { } vector syntax is discontinued

In [6]:
C =[[1,2,3],[1,2]]

2-element Array{Array{Int64,1},1}:
 [1,2,3]
 [1,2]  

In [7]:
typeof(C)


Array{Array{Int64,1},1}

In [9]:
C[3]=[1,2,4]

3-element Array{Int64,1}:
 1
 2
 4

In [10]:
C


5-element Array{Array{Int64,1},1}:
    [1,2,3]
    [1,2]  
    [1,2,4]
 #undef    
 #undef    

In [23]:
b=[ 0]



1-element Array{Int64,1}:
 0

In [24]:
b[1]=[2;5]

LoadError: MethodError: Cannot `convert` an object of type Array{Int64,1} to an object of type Int64
This may have arisen from a call to the constructor Int64(...),
since type constructors fall back to convert methods.

In [25]:
?getindex



search: getindex broadcast_getindex



```
getindex(type[, elements...])
```

Construct a 1-d array of the specified type. This is usually called with the syntax `Type[]`. Element values can be specified using `Type[a,b,c,...]`.

```
getindex(A, inds...)
```

Returns a subset of array `A` as specified by `inds`, where each `ind` may be an `Int`, a `Range`, or a `Vector`. See the manual section on [array indexing](:ref:`array indexing <man-array-indexing>`) for details.

```
getindex(collection, key...)
```

Retrieve the value(s) stored at the given key or index within a collection. The syntax `a[i,j,...]` is converted by the compiler to `getindex(a, i, j, ...)`.


In [26]:
a=()

()

In [27]:
a[0]

LoadError: BoundsError: attempt to access ()
  at index [0]

In [28]:
?append!

search: append!



```
append!(collection, collection2) -> collection.
```

Add the elements of `collection2` to the end of `collection`.

```jldoctest
julia> append!([1],[2,3])
3-element Array{Int64,1}:
 1
 2
 3
```

```jldoctest
julia> append!([1, 2, 3], [4, 5, 6])
6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6
```

Use [`push!`](:func:`push!`) to add individual items to `collection` which are not already themselves in another collection. The result is of the preceding example is equivalent to `push!([1, 2, 3], 4, 5, 6)`.
