## Algoritmo pra matriz tridiagonal (Algoritmo de Thomas)

Uma matriz $n\times n$ é tridiagonal quando os únicos elementos diferentes de zero zero são:
 * $a_{ii} = q_i$ para $ 1\leq i \geq n$
 * $a_{i+1i}= s_i$ para $i \leq n-1$
 * $a_{ii+1} =r_i$ para $i \leq n-1$
 
Para resolver o sistema $Ax=b$ vamos usar o seguinte algoritmo que está codificado em julia



In [33]:
function tridiagonal(s,q,r,b)
    n=length(b)
    # 1. triangularização
    for i in 1:n-1
        m= s[i]/q[i]
        q[i+1]= q[i+1]-m*r[i]
        b[i+1]=b[i+1]-m*b[i] # note que esta linha resolve o sistema Ly = b de cima pra baixo e guarda a soluçaão em b
    end
    # 2. Resolução de baixo para cima
    x=zeros(n)
    x[n]=b[n]/q[n]
    for i in reverse(1:n-1)
        x[i]=(b[i]-r[i]*x[i+1])/q[i]
    end
    return x
end

tridiagonal (generic function with 1 method)

In [27]:
# Exemplo
A = [2. -1. 0. 0.; -1. 2. -1. 0. ; 0 -1 2 -1 ; 0 0 -1 2]

4×4 Array{Float64,2}:
  2.0  -1.0   0.0   0.0
 -1.0   2.0  -1.0   0.0
  0.0  -1.0   2.0  -1.0
  0.0   0.0  -1.0   2.0

In [28]:
q = [A[i,i] for i in 1:4]
s= [A[i+1,i] for i in 1:3]
r= [A[i,i+1] for i in 1:3 ]

3-element Array{Float64,1}:
 -1.0
 -1.0
 -1.0

In [29]:
b = [1.,2,3,4]

4-element Array{Float64,1}:
 1.0
 2.0
 3.0
 4.0

In [30]:
q,r,s,b

([2.0,2.0,2.0,2.0],[-1.0,-1.0,-1.0],[-1.0,-1.0,-1.0],[1.0,2.0,3.0,4.0])

In [31]:
x=tridiagonal(s,q,r,b)

4-element Array{Float64,1}:
 4.0
 7.0
 8.0
 6.0

In [32]:
  A*x


4-element Array{Float64,1}:
 1.0
 2.0
 3.0
 4.0